project:
  type: book
  output-dir: _book

book:
  title: "Statistical Audit Sampling with R"
  author: "Koen Derks"
  date: "12/19/2022"
  reader-mode: true

  page-footer:
    left: |
      Statistical Audit Sampling with R was written by Koen Derks.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://koenderks.github.io/sasr/
  repo-url: https://github.com/koenderks/sasr/
  repo-branch: master
  repo-actions: [edit, source, issue]
  chapters:
    - index.qmd
    - ch00.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd
    - ch04.qmd
    - ch05.qmd
    - ch06.qmd
    - ch07.qmd
    - chref.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - sasr.scss
    code-link: true
  epub:
    cover-image: cover.png

    author-meta: "Koen Derks"
    callout-appearance: simple

editor: visual
