project:
  type: book
  output-dir: _book

author-meta: Koen Derks
editor: visual
bibliography: references.bib
csl: apa.csl

book:
  title: Statistical Audit Sampling with R
  author:
    - name: Koen Derks
      orcid: 0000-0002-5533-9349
      corresponding: true
  date: today
  page-navigation: true
  reader-mode: false
  cover-image: cover.png
  favicon: cover.png
  site-url: https://koenderks.github.io/sasr/
  repo-url: https://github.com/koenderks/sasr/
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - preface.qmd
    - part: part-1.qmd
      chapters:
      - r-intro.qmd
      - info.qmd
    - part: part-2.qmd
      chapters:
      - planning.qmd
      - selection.qmd
      - evaluation.qmd
      - stratified-evaluation.qmd
    - part: part-3.qmd
      chapters:
      - software.qmd
    - references.qmd
  page-footer:
    left: |
      Statistical Audit Sampling with R was written by Koen Derks.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: On this page
    smooth-scroll: true
    theme:
      - cosmo
      - sasr.scss
    code-link: true
  pdf:
    documentclass: scrbook
    papersize: a5paper
    toc: true
    toc-depth: 2
    toc-title: Contents
  epub:
    toc: true
    tod-depth: 2
    toc-title: Contents
