project:
  type: book
  output-dir: _book
author-meta: Koen Derks
editor: visual
bibliography: references.bib
csl: apa.csl
book:
  title: Statistical Audit Sampling with R
  author:
    - name: Koen Derks
      orcid: 0000-0002-5533-9349
      corresponding: true
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: front-page.svg
  favicon: front-page.png
  site-url: https://koenderks.github.io/sasr/
  repo-url: https://github.com/koenderks/sasr/
  repo-branch: master
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  open-graph: true
  page-navigation: true
  reader-mode: true
  search: false
  twitter-card:
    image: "front-page.svg"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: The Basics
      chapters:
      - chap-foundations.qmd
      - chap-inference.qmd
    - part: Workflow
      chapters:
      - chap-planning.qmd
      - chap-selection.qmd
      - chap-evaluation.qmd
      - chap-stratified-evaluation.qmd
    - part: Software
      chapters:
      - chap-jasp.qmd
      - chap-packages.qmd
    - references.qmd
    - tutorial.qmd
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: On this page
    smooth-scroll: true
    code-link: true
    code-overflow: wrap
    code-tools: true
    theme:
      - cosmo
      - sasr.scss
  pdf:
    documentclass: book
    extra_dependencies: ["float"]
    include-in-header:
      text: |
        \pagenumbering{arabic}
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
          \usepackage{tikz}
          \renewcommand{\frontmatter}{%
              \thispagestyle{empty}%
              \begin{tikzpicture}[remember picture,overlay]
              \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{front-page.pdf}};
              \end{tikzpicture}%
          }
          \renewcommand{\backmatter}{%
              \thispagestyle{empty}%
              \begin{tikzpicture}[remember picture,overlay]
              \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{back-page.pdf}};
              \end{tikzpicture}%
          }
          \renewcommand{\mainmatter}{\clearpage}
          \renewcommand{\maketitle}{}
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhead{}
          \fancyhead[RO,LE]{\leftmark}
          \fancyfoot{}
          \fancyfoot[C]{\thepage}
          \setkeys{Gin}{width=0.75\textwidth}
    keep-tex: false
    classoption: [10pt,twoside]
    pagestyle: headings
    geometry:
      - twoside
      - left = 25mm
      - right = 25mm
      - bottom = 19.05mm
      - top = 12.7mm
      - paperwidth = 180mm
      - paperheight = 254mm
      - includehead
      - includefoot
    fontfamily: libertinus
    toc-title: Contents
    toc-depth: 2
    toc: true
    number-sections: true
