project:
  type: book
  output-dir: _book

author-meta: Koen Derks
editor: visual
bibliography: references.bib
csl: apa.csl

book:
  title: Statistical Audit Sampling with R
  author:
    - name: Koen Derks
      orcid: 0000-0002-5533-9349
      corresponding: true
  date: today

  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.svg
  favicon: cover.png
  site-url: https://koenderks.github.io/sasr/
  repo-url: https://github.com/koenderks/sasr/
  repo-branch: master
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  open-graph: true
  page-navigation: true
  reader-mode: false
  twitter-card:
    image: "cover.svg"
  search:
    limit: 20
    collapse-after: 2
    copy-button: true
  chapters:
    - index.qmd

    - introduction.qmd

    - part: part-basics.qmd
      chapters:
      - chap-r.qmd
      - chap-info.qmd

    - part: part-workflow.qmd
      chapters:
      - chap-planning.qmd
      - chap-selection.qmd
      - chap-evaluation.qmd
      - chap-stratified-evaluation.qmd

    - part: part-software.qmd
      chapters:
      - chap-jasp.qmd
      - chap-packages.qmd

    - references.qmd

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: On this page
    smooth-scroll: true
    code-link: true
    code-overflow: wrap
    code-tools: true
    theme:
      - cosmo
      - sasr.scss
