project:
  type: book
  output-dir: _book

author-meta: Koen Derks
editor: visual
bibliography: references.bib
csl: apa.csl

book:
  title: Statistical Audit Sampling with R
  author:
    - name: Koen Derks
      orcid: 0000-0002-5533-9349
      corresponding: true
  date: today
  reader-mode: false
  cover-image: cover.png
  favicon: cover.png
  site-url: https://koenderks.github.io/sasr/
  repo-url: https://github.com/koenderks/sasr/
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - ch00.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd
    - ch04.qmd
    - ch05.qmd
    - ch06.qmd
    - ch07.qmd
    - chref.qmd
  page-footer:
    left: |
      Statistical Audit Sampling with R was written by Koen Derks.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    theme:
      - cosmo
      - sasr.scss
    code-link: true
  epub:
    cover-image: cover.png
