---
output:
  bookdown::html_document2:
    fig_caption: yes
editor_options:
  chunk_output_type: console
---

```{r echo = FALSE, cache = FALSE}
source("utils.R", local = TRUE)
```

# Background Information {#CHAPTER-2}

Auditors use audit sampling as a way to evaluate a portion of transactions or
items within a population in order to make conclusions about the population as a
whole. It is a cost-effective method for testing the accuracy and reliability of
financial information because it allows auditors to test a representative sample
of the population instead of the entire population.

In the realm of auditing, sampling becomes necessary when the truth about a
population is not readily accessible or discernible through other means. With
the advent of modern technology, auditors often have access to an abundance of
information about a population, which sometimes enables them to perform integral
testing. Nonetheless, there are situations where a sample is still necessary due
to the unavailability of complete data. For instance, an auditor may utilize
analytical procedures to verify the consistency of payments with payment orders,
but then must subsequently confirm the validity of these orders through detailed
testing.

In auditing, there are two primary methods of sampling: statistical and
non-statistical. Statistical sampling involves using probability theory to
select a sample from the population and draw conclusions about the population
based on the sample. Non-statistical sampling, on the other hand, is based on
the auditor's professional judgment and does not use statistical inference to
come to a conclusion. This book does not cover non-statistical sampling.

The way that statistical sampling should be performed is prescribed by 
international auditing standards. The next section discusses what these
standards say about statistical sampling..

## Auditing Standards

There are three auditing standards related to staistical audit sampling:

- [ISA 530](https://www.ifac.org/system/files/downloads/a027-2010-iaasb-handbook-isa-530.pdf): 
  Auditing standard for international firms published by the International
  Auditing and Assurance Standards Board (IAASB).
- [AU-C 530](https://www.aicpa.org/content/dam/aicpa/research/standards/auditattest/downloadabledocuments/au-c-00530.pdf): 
  Auditing standard for private firms published by the American Institute of
  Certified Public Accountants (AICPA).
- [AS 2315](https://pcaobus.org/oversight/standards/auditing-standards/details/AS2315): 
  Auditing standard for public firms published by the Public Company
  Accounting Oversign Board (PCAOB).

All three standards describe statistical sampling in a similar manner. For
example, ISA 530 [@ISA530] describes statistical audit sampling as an approach
that, at least, has the following two characteristics:

- Random selection of sample items,
- The use of an appropriate statistical technique to evaluate sample results,
  including measurement of sampling risk

Any sampling approach that does not have these characteristics is considered
nonstatistical sampling by the auditing standards.

In practice, statistical sampling should be used in a way that is tailored to
the specific circumstances of the audit. This may include considering factors
such as the size and complexity of the population, the materiality of the items
being tested, and the degree of inherent risk in the audit area. The auditor
should also document the sampling process in order to demonstrate that it was
conducted compliant with auditing standards. The next section discusses these
important concepts in statistical audit sampling.

## Important Concepts

### Population

In statistical audit sampling, the auditor first defines the population and the
sampling units, which is the unit of measurement for the population
(e.g., transactions, invoices, etc.). The auditor then selects a sample from the
population using a specified sampling method, such as random sampling or
stratified sampling.

### Tolerable Misstatement

### Tolerable Deviation Rate

### Sampling risk

One important concept in statistical audit sampling is the sampling risk. The
confidence level is the probability that the sample estimate falls within a
certain range of the true population value. For example, if the confidence level
is 95%, there is a 95% probability that the sample estimate is within the
specified range of the true population value. The confidence level is inversely
related to the audit risk $\alpha$, as follows:

$$\text{Confidence} = 1 - \text{Audit risk}(\alpha)$$

Hence, the desired confidence level is known to the auditor before they start
with their audit sampling activities.

Another important concept in statistical audit sampling is precision. Precision
refers to the degree to which the auditors' inferences are reliable. An estimate
with high precision is more likely to provide accurate conclusions about the
population. The precision of an estimate can be improved by increasing the
sample size.

### Sample Size

### Recap

To recap, the basic statistical concepts behind statistical audit sampling
introduced in this chapter are:

- **Population**: The entire set of data from which a sample is selected and
  about which the auditor wishes to draw conclusions.
- **Tolerable misstatement**: This is the maximum amount of misstatement that
  the auditor is willing to accept in the population. A larger tolerable
  misstatement may require a larger sample size to achieve a desired level of
  assurance.
- **Tolerable deviation rate**: A rate of deviation set by the auditor in
  respect of which the auditor seeks to obtain an appropriate level of assurance
  that the rate of deviation set by the auditor is not exceeded by the actual
  rate of deviation in the population.
- **Sampling risk**: The risk that the auditor's conclusion based on a sample
  may be different from the conclusion if the entire popula- tion were subjected
  to the same audit procedure. Sampling risk can lead to two types of erroneous
  conclusions: a Type-I error or a Type-II error.
- **Sample size**: The sample size should be large enough to provide a reliable
  estimate of the population characteristics, but not so large that it is
  impractical to review.

## Classical Inference

The classical (frequentist) and the Bayesian approach to statistical inference
are two different ways to use data to perform inferences or draw conclusions
about a population. Both paradigms have their own set of assumptions and
approaches to statistical estimation and hypothesis testing.

### Estimation

Classical statistics is based on the concept of probability as a frequency. It
is the traditional approach to statistical analysis and relies on the idea that
probability is the long-term frequency of an event occurring in a large number
of trials. This approach is based on the law of large numbers, which states that
as the number of trials increases, the frequency of an event will approach the
true probability of the event occurring. In frequentist estimation, the
parameter that needs to be estimated is considered to be fixed, but unknown. The
goal of frequentist estimation is to use the sample data to find the value of
the parameter that is most likely to be true. This is typically done using point
estimates, which are single values that are thought to be the best estimate of
the population parameter, and interval estimates, which provide a range of
values that the population parameter is likely to fall within.

### Hypothesis Testing

## Bayesian Inference

Bayesian estimation, on the other hand, is based on the idea that the parameter
of interest is not fixed but uncertain. In this approach, the parameter is 
onsidered to be a random variable with a certain distribution, and the goal is
to use the data and prior knowledge about the parameter to update our belief
about its value. This is typically done using Bayes' theorem, which states that
the posterior probability (i.e., the updated belief about the parameter after
seeing the data) is equal to the prior probability (i.e., the belief about the
parameter before seeing the data) times the likelihood (i.e., the probability of
the data given the parameter).

### Estimation

One major difference between classical and Bayesian statistics is the way
they handle uncertainty. In classical statistics, uncertainty is represented
by the standard error of an estimate, which is a measure of the precision of an
estimate. In Bayesian statistics, uncertainty is represented by the posterior
distribution, which is a distribution of the possible values of the population
parameter given the sample data and our prior beliefs. Bayesian inferences
uses uses Bayes' theorem to update the prior beliefs about the population
parameter with the new information from the sample data. Bayes' theorem is given
by the following formula:

$$p(\theta \,|\, y) = \frac{p(y \,|\, \theta)p(\theta)}{p(y)}$$

where $p(\theta \,|\, y)$ is the posterior probability of the population
parameter $\theta$ given the sample data $y$, $p(y \,|\, \theta)$ is the
likelihood of the sample data given $\theta$, $p(\theta)$ is the prior
probability of $\theta$, and $p(y)$ is the total probability of the sample data
occurring. Because with a fixed sample $p(y)$ is a constant, Bayes' theorem is
often given as follows:

$$p(\theta \,|\, y) \propto p(y \,|\, \theta) \times p(\theta)$$

or, in words:

$$\text{Posterior} \propto \text{Likelihood} \times \text{Prior}$$

There are several other differences between classical and Bayesian approaches.
One major difference is that classical approaches focus on the long-run
behavior of an estimator, while Bayesian approaches focus on the probability of
the estimator being correct given the data. Another difference is that
classical approaches rely on asymptotic results (i.e., results that hold in
the limit as the sample size goes to infinity), while Bayesian approaches can be
applied with any sample size. Additionally, Bayesian approaches allow for the
incorporation of prior knowledge about the parameter, while classical
approaches do not.

Overall, classical and Bayesian statistics are two different approaches to
statistical analysis that have their own unique strengths and weaknesses.
Classical statistics is a well-established approach that is widely used in
scientific research and audit practice, but it has some limitations, such as its
reliance on assumptions and its inability to incorporate prior beliefs. Bayesian
statistics is a newer approach that allows for more flexibility in statistical
inferences, but it requires the specification of prior beliefs, which can be
difficult to quantify.

### Hypothesis Testing

The Bayes factor is a measure used in Bayesian inference to compare the relative
strength of evidence between two competing hypotheses. The Bayes factor is
calculated by comparing the probability of the observed data given each of the
two competing hypotheses. This probability is known as the likelihood of the
data. The Bayes factor is then the ratio of the likelihood of the data under one
hypothesis to the likelihood of the data under the other hypothesis. The Bayes
factor can be used in the context of an audit, where the auditor is trying to
determine the likelihood that a particular financial statement is represented
fairly or not.

For example, an auditor might be evaluating the fairness of a company's
financial statements for the year. They have two hypotheses: the first is that
the statements are accurate, and the second is that the statements are not
accurate. The auditor gathers data from a statistical audit sample and uses this
data to calculate the Bayes factor.

The Bayes factor is calculated by taking the ratio of the probability of the
first hypothesis (that the statements are accurate) given the observed data, to
the probability of the second hypothesis (that the statements are not accurate)
given the observed data. The higher the Bayes factor, the more likely it is that
the first hypothesis is true.

The Bayes factor can be used to assess the strength of evidence for one
hypothesis over the other and to determine which hypothesis is more likely to
be true given the observed data. It is often used in scientific research to help
evaluate the validity of different hypotheses and to make informed decisions
based on the available evidence. For auditors, the Bayes factor can be a useful
tool to determine the likelihood of different hypotheses being true based on the
data they have collected, and it can help them make informed decisions about the
fairness of the financial statements.

For example, if the Bayes factor is 5, this means that the probability of the
statements being accurate given the observed data is 5 times higher than the
probability of them being not accurate. In this case, the auditor would be more
likely to conclude that the financial statements are accurate.

The **jfa** package can help us to calculate Bayes factors for and against the
hypothesis that the financial statements are represented fairly.
