<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Koen Derks">

<title>Statistical Audit Sampling with R - 3&nbsp; Planning a Sample</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ch04.html" rel="next">
<link href="./ch02.html" rel="prev">
<link href="./cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Planning a Sample</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Audit Sampling with R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/koenderks/sasr/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch00.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch01.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch02.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Background Information</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch03.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Planning a Sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch04.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Selecting a Sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch05.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Evaluating a Sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch06.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Evaluating a Stratified Sample</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ch07.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Other Software</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chref.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#required-information" id="toc-required-information" class="nav-link active" data-scroll-target="#required-information"><span class="toc-section-number">3.1</span>  Required Information</a></li>
  <li><a href="#the-hypergeometric-likelihood" id="toc-the-hypergeometric-likelihood" class="nav-link" data-scroll-target="#the-hypergeometric-likelihood"><span class="toc-section-number">3.2</span>  The Hypergeometric Likelihood</a>
  <ul class="collapse">
  <li><a href="#classical-planning" id="toc-classical-planning" class="nav-link" data-scroll-target="#classical-planning"><span class="toc-section-number">3.2.1</span>  Classical planning</a></li>
  <li><a href="#bayesian-planning" id="toc-bayesian-planning" class="nav-link" data-scroll-target="#bayesian-planning"><span class="toc-section-number">3.2.2</span>  Bayesian Planning</a></li>
  </ul></li>
  <li><a href="#the-binomial-likelihood" id="toc-the-binomial-likelihood" class="nav-link" data-scroll-target="#the-binomial-likelihood"><span class="toc-section-number">3.3</span>  The Binomial Likelihood</a>
  <ul class="collapse">
  <li><a href="#classical-planning-1" id="toc-classical-planning-1" class="nav-link" data-scroll-target="#classical-planning-1"><span class="toc-section-number">3.3.1</span>  Classical Planning</a></li>
  <li><a href="#bayesian-planning-1" id="toc-bayesian-planning-1" class="nav-link" data-scroll-target="#bayesian-planning-1"><span class="toc-section-number">3.3.2</span>  Bayesian Planning</a></li>
  </ul></li>
  <li><a href="#the-poisson-likelihood" id="toc-the-poisson-likelihood" class="nav-link" data-scroll-target="#the-poisson-likelihood"><span class="toc-section-number">3.4</span>  The Poisson Likelihood</a>
  <ul class="collapse">
  <li><a href="#classical-planning-2" id="toc-classical-planning-2" class="nav-link" data-scroll-target="#classical-planning-2"><span class="toc-section-number">3.4.1</span>  Classical planning</a></li>
  <li><a href="#bayesian-planning-2" id="toc-bayesian-planning-2" class="nav-link" data-scroll-target="#bayesian-planning-2"><span class="toc-section-number">3.4.2</span>  Bayesian Planning</a></li>
  </ul></li>
  <li><a href="#practical-examples" id="toc-practical-examples" class="nav-link" data-scroll-target="#practical-examples"><span class="toc-section-number">3.5</span>  Practical Examples</a>
  <ul class="collapse">
  <li><a href="#audit-risk-model" id="toc-audit-risk-model" class="nav-link" data-scroll-target="#audit-risk-model"><span class="toc-section-number">3.5.1</span>  Audit Risk Model</a></li>
  <li><a href="#benchmark-analysis" id="toc-benchmark-analysis" class="nav-link" data-scroll-target="#benchmark-analysis"><span class="toc-section-number">3.5.2</span>  Benchmark Analysis</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/koenderks/sasr/edit/master/ch03.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/koenderks/sasr/blob/master/ch03.qmd" class="toc-action">View source</a></p><p><a href="https://github.com/koenderks/sasr/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="CHAPTER-3" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Planning a Sample</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">

</div>
<p>One of the key considerations in audit sampling is determining the appropriate sample size to achieve a desired level of assurance or precision. This chapter will focus on three standard likelihoods commonly used in audit sampling: the hypergeometric likelihood, the binomial likelihood, and the Poisson likelihood.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/planning.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure 3.1: The standard audit sampling workflow consists of four stages: planning, selection, execution, and evaluation. The planning stage is the first of these stages.</figcaption><p></p>
</figure>
</div>
<p>In <strong>jfa</strong>, determining an appropriate sample size is achieved via the <code>planning()</code> function.</p>
<section id="required-information" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="required-information"><span class="header-section-number">3.1</span> Required Information</h2>
<p>First, planning a minimum sample requires knowledge of the conditions that lead to acceptance or rejection of the population (i.e., the sampling objectives). Typically, sampling objectives can be classified into one or both of the following:</p>
<ul>
<li><strong>Hypothesis testing</strong>: The goal of the sample is to obtain evidence for or against the claim that the misstatement in the population is lower than a given value (i.e., the performance materiality).</li>
<li><strong>Estimation</strong>: The goal of the sample is to obtain an accurate estimate of the misstatement in the population (with a minimum precision).</li>
</ul>
<p>Second, it is advised to specify the expected (or tolerable) misstatements in the sample. The expected misstatements are the misstatements that you allow in the sample, while still retaining the desired amount of assurance about the population. It is strongly recommended to set the value for the expected misstatements in the sample conservatively to minimize the chance of the observed misstatements in the sample exceeding the expected misstatements, which would imply that insufficient work has been done in the end.</p>
<p>Finally, next to determining the sampling objective(s) and the expected misstatements, it is important to determine the statistical distribution linking the sample outcomes to the population misstatement. This distribution is called the likelihood (i.e., <code>poisson</code>, <code>binomial</code>, or <code>hypergeometric</code>). All three aforementioned likelihoods are commonly used in an audit sampling context, however, <code>poisson</code> is the default likelihood in <strong>jfa</strong> because it is the most conservative of the three. In the subsections below, we elaborate on the three standard likelihoods for audit sampling and demonstrate how they can be used to obtain a minimum sample size.</p>
</section>
<section id="the-hypergeometric-likelihood" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="the-hypergeometric-likelihood"><span class="header-section-number">3.2</span> The Hypergeometric Likelihood</h2>
<p>Let’s consider how to use the hypergeometric likelihood to calculate the minimum sample size needed to achieve the desired level of assurance. The hypergeometric distribution is a discrete probability distribution that is commonly used to model the number of events occurring in a fixed number of trials when the population size is known. It assumes that samples are drawn from the population without replacement, and is therefore the likelihood that most closely resembles the audit practice. For our purpose, we can use the hypergeometric distribution as a likelihood to model the number of misstatements that are expected to be found in the sample.</p>
<p>The probability mass function (PMF) of the hypergeometric distribution is given by:</p>
<p><span class="math display">\[\begin{equation}
  p(X=k)=\frac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}},
\end{equation}\]</span></p>
<p>where <span class="math inline">\(k\)</span> is the number of misstatements in the sample, <span class="math inline">\(n\)</span> is the sample size, <span class="math inline">\(N\)</span> is the population size and <span class="math inline">\(K\)</span> is the total number of misstatements assumed in the population. The assumed misstatements <span class="math inline">\(K\)</span> is a linear extrapolation of the assumed misstatement rate in the population <span class="math inline">\(\theta_{max}\)</span> to the total population:</p>
<p><span class="math display">\[\begin{equation}
  K = \theta_{max} N.
\end{equation}\]</span></p>
<section id="classical-planning" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="classical-planning"><span class="header-section-number">3.2.1</span> Classical planning</h3>
<p>Concretely, the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{equation}
  k \sim \text{Hypergeometric}(n, N, K)
\end{equation}\]</span></p>
<p>Given the performance materiality <span class="math inline">\(\theta_{max}\)</span>, we can solve for the minimum sample size <span class="math inline">\(n\)</span> needed to achieve this assurance level. This sample size is dependent on the number of misstatements that the auditor expects, or tolerates, in the sample.</p>
<section id="no-expected-misstatement" class="level4" data-number="3.2.1.1">
<h4 data-number="3.2.1.1" class="anchored" data-anchor-id="no-expected-misstatement"><span class="header-section-number">3.2.1.1</span> No Expected Misstatement</h4>
<p>If the auditor does not expect any misstatements in the sample, they can set <span class="math inline">\(k = 0\)</span>, which consequently determines how the sample size can be calculated. For example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span> in a population of <span class="math inline">\(N = 1000\)</span> items, then the required sample size under the assumption of no expected misstatements in the sample is <span class="math inline">\(n = 94\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-2_dad6005f1f2cd0931463bc716f73df23">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"hypergeometric"</span>, <span class="at">N.units =</span> <span class="dv">1000</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 94 </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 95 iterations via method 'hypergeometric'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The sample size of 94 can be confirmed by checking that 94 is the minimum integer that results in less than 5% probability of finding 0 misstatements, given the assumption that the population misstatement is truly 3%. The <code>dhyper()</code> function calculates the probability of observing <span class="math inline">\(k\)</span> missatements in a sample of <span class="math inline">\(n\)</span> items given the assumed hypergeometric distribution with <span class="math inline">\(N\)</span> items and <span class="math inline">\(K\)</span> assumed misstatements in the population.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-3_fc19175319a28505720a051e6fb2a6c9">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(<span class="fl">0.03</span> <span class="sc">*</span> <span class="dv">1000</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dhyper</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">m =</span> K, <span class="at">n =</span> <span class="dv">1000</span> <span class="sc">-</span> K, <span class="at">k =</span> <span class="dv">93</span>) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 93: Not sufficient</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dhyper</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">m =</span> K, <span class="at">n =</span> <span class="dv">1000</span> <span class="sc">-</span> K, <span class="at">k =</span> <span class="dv">94</span>) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 94: Sufficient</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can make this sample size visually intuitive by showing thehypergeometric(<span class="math inline">\(k\)</span> | 94, 1000, 30) distribution and highlighting the probability for <span class="math inline">\(k = 0\)</span>. This probability is lower than the required sampling risk <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-4_43cd57e1f0c4098bbd912f2a9930e175">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="expected-misstatements" class="level4" data-number="3.2.1.2">
<h4 data-number="3.2.1.2" class="anchored" data-anchor-id="expected-misstatements"><span class="header-section-number">3.2.1.2</span> Expected Misstatements</h4>
<p>If the auditor expects misstatements in the sample, they can set <span class="math inline">\(k\)</span> to any integer value, which consequently determines how the sample size can be calculated. As another example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span> in a population of <span class="math inline">\(N = 1000\)</span> items, then the required sample size under the assumption of one expected misstatement in the sample is <span class="math inline">\(n = 147\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-5_2c7f07848b2a7c3c50d218abdb53ef92">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">1</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"hypergeometric"</span>, <span class="at">N.units =</span> <span class="dv">1000</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 147 </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 146 iterations via method 'hypergeometric'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once again, the sample size of 147 can be confirmed by checking that 147 is the minimum integer that results in less than 5% probability of finding 0 or 1 misstatements, given the assumption that that the population misstatement is truly 3%.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-6_5915e89da5f708df094e325a500a7c51">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dhyper</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">m =</span> K, <span class="at">n =</span> <span class="dv">1000</span> <span class="sc">-</span> K, <span class="at">k =</span> <span class="dv">146</span>)) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 146: Not sufficient</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dhyper</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">m =</span> K, <span class="at">n =</span> <span class="dv">1000</span> <span class="sc">-</span> K, <span class="at">k =</span> <span class="dv">147</span>)) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 147: Sufficient</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like before, we can make this sample size visually intuitive by showing the hypergeometric(<span class="math inline">\(k\)</span> | 147, 1000, 30) distribution and highlighting the probabilities for <span class="math inline">\(k = 0\)</span> and <span class="math inline">\(k = 1\)</span>. The sum of these probabilities is lower than the required sampling risk <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-7_a0e4b7ad474edf97ce08e8579e51ce7d">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="bayesian-planning" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="bayesian-planning"><span class="header-section-number">3.2.2</span> Bayesian Planning</h3>
<p>Performing Bayesian planning with the hypergeometric likelihood <span class="citation" data-cites="Dyer1993">(<a href="chref.html#ref-Dyer1993" role="doc-biblioref">Dyer &amp; Pierce, 1993</a>)</span> requires that you specify a prior distribution for the parameter <span class="math inline">\(\theta\)</span>. Practically, this means that you should provide an input for the <code>prior</code> argument in the <code>planning()</code> function.</p>
<p>Setting <code>prior = TRUE</code> performs Bayesian planning using a <a href="https://koenderks.github.io/jfa/articles/creating-prior.html#default-priors-method-default">default prior</a> conjugate to the specified <code>likelihood</code> (i.e., a beta-binomial prior). Concretely, this means that the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{align}
  k &amp;\sim \text{Hypergeometric}(n, N, K) \\
  K &amp;\sim \text{Beta-binomial}(N, \alpha, \beta)
\end{align}\]</span></p>
<blockquote class="blockquote">
<p>The beta-binomial prior distribution is conjugate to the hypergeometric likelihood (see this <a href="https://en.wikipedia.org/wiki/Conjugate_prior#Table_of_conjugate_distributions">list</a> of conjugate priors), which means that the posterior distribution of <span class="math inline">\(K\)</span> can be determined analytically. For example, if the prior distribution for <span class="math inline">\(K\)</span> is beta-binomial(<span class="math inline">\(N\)</span>, <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>) and the auditor has observed a sample of <span class="math inline">\(n\)</span> items containing <span class="math inline">\(k\)</span> misstatements, the posterior distribution for <span class="math inline">\(K\)</span> is beta-binomial(<span class="math inline">\(N - n\)</span>, <span class="math inline">\(\alpha + k\)</span>, <span class="math inline">\(\beta + n - k\)</span>).</p>
</blockquote>
<p>For example, the command below uses a default beta-binomial(<span class="math inline">\(N\)</span>, 1, 1) prior distribution to plan the sample, since <code>planning()</code> is given the hypergeometric likelihood. If we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span> in a population of <span class="math inline">\(N = 1000\)</span> items, then the required sample size under the assumption of zero expected misstatements in the sample is <span class="math inline">\(n = 93\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-8_874f53730d0baba2bce9140cbcc1859c">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plan <span class="ot">&lt;-</span> <span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">likelihood =</span> <span class="st">"hypergeometric"</span>, <span class="at">N.units =</span> <span class="dv">1000</span>, <span class="at">prior =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plan)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning Summary</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Confidence level:              0.95 </span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Population size:               1000 </span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Materiality:                   0.03 </span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Hypotheses:                    H₀: Θ &gt; 0.03 vs. H₁: Θ &lt; 0.03 </span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected:                      0 </span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    hypergeometric </span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Prior distribution:            beta-binomial(N = 1000, α = 1, β = 1) </span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Minimum sample size:           93 </span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Tolerable errors:              0 </span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Posterior distribution:        beta-binomial(N = 907, α = 1, β = 94) </span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected most likely error:    0 </span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected upper bound:          0.029 </span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected precision:            0.029 </span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected BF₁₀:                 620.58</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can inspect how the prior distribution compares to the expected posterior distribution by using the <code>plot()</code> function. The expected posterior distribution is the posterior distribution that would occur if you actually observed the planned sample containing the expected misstatements.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-9_4162a6df1f0f9c04fd4caf7421331dfe">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Note that the hypergeometric likelihood does not allow for non-conjugate prior distributions to be used as a prior.</p>
</section>
</section>
<section id="the-binomial-likelihood" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="the-binomial-likelihood"><span class="header-section-number">3.3</span> The Binomial Likelihood</h2>
<p>Let’s consider how to use the binomial likelihood to calculate the minimum sample size needed to achieve a desired level of assurance. The binomial distribution is a discrete probability distribution that is commonly used to model the number of events occurring in a fixed number of trials. It is similar to the hypergeometric distribution, however, it assumes that samples are drawn from the population with replacement. For our purpose, we can use the binomial distribution as a likelihood to model the number of misstatements that are expected to be found in the sample.</p>
<blockquote class="blockquote">
<p>In audit sampling, the binomial likelihood is often used to approximate the hypergeometric likelihood since it is easier to work with (i.e., it only has two parameters: <span class="math inline">\(\theta\)</span> and <span class="math inline">\(n\)</span>, while the hypergeometric has three: <span class="math inline">\(n\)</span>, <span class="math inline">\(N\)</span>, and <span class="math inline">\(K\)</span>). However, the binomial likelihood is more conservative than the hypergeometric likelihood, meaning that resulting sample sizes will be higher.</p>
</blockquote>
<p>The probability mass function (PMF) of the binomial distribution is given by:</p>
<p><span class="math display">\[\begin{equation}
  p(k; n, \theta) = \binom{n}{k} \theta^{k} (1-\theta)^{n - k},
\end{equation}\]</span></p>
<p>where <span class="math inline">\(k\)</span> is the number of misstatements in the sample, <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(\theta\)</span> is the probability of misstatement in the population.</p>
<section id="classical-planning-1" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="classical-planning-1"><span class="header-section-number">3.3.1</span> Classical Planning</h3>
<p>Concretely, the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{equation}
  k \sim \text{Binomial}(n, \theta_{max})
\end{equation}\]</span></p>
<section id="no-expected-misstatement-1" class="level4" data-number="3.3.1.1">
<h4 data-number="3.3.1.1" class="anchored" data-anchor-id="no-expected-misstatement-1"><span class="header-section-number">3.3.1.1</span> No Expected Misstatement</h4>
<p>If the auditor does not expect any misstatements in the sample, they can set <span class="math inline">\(k = 0\)</span>, which consequently determines how the sample size can be calculated. Given a performance materiality <span class="math inline">\(\theta_{max}\)</span>, we can solve for the minimum sample size <span class="math inline">\(n\)</span> needed to achieve a certain assurance level. A useful trick to utilize is that, if we do not expect any misstatements in the sample, the formula for the minimum required sample size reduces to:</p>
<p><span class="math display">\[\begin{equation}
  n = \lceil\frac{\ln(\alpha)}{\ln(1 - \theta_{max})}\rceil.
\end{equation}\]</span></p>
<blockquote class="blockquote">
<p><span class="math inline">\(\lceil...\rceil\)</span> is the ceiling function. Hence, <span class="math inline">\(\lceil1.2\rceil = 2\)</span>.</p>
</blockquote>
<p>For example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha=0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of zero expected misstatements in the sample is <span class="math inline">\(n = 99\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-10_ef2cd98cb517b182ee506f3480b44c1e">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(<span class="fu">log</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.03</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 99</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <strong>jfa</strong>, this sample size can be replicated using the following code:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-11_890ec01eb19cc169df5f5d792b435228">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"binomial"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 99 </span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 100 iterations via method 'binomial'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The sample size of 99 can be confirmed by checking that 99 is the minimum integer that results in less than 5% probability of finding 0 misstatements, given the assumption that the population misstatement is truly 3%. The <code>dbinom()</code> function calculates the probability of observing <span class="math inline">\(k\)</span> missatements in a sample of <span class="math inline">\(n\)</span> items given an assumed misstatement probability <span class="math inline">\(\theta_{max}\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-12_7076b96847dce51926d6dd05cdf8af6c">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">98</span>, <span class="at">prob =</span> <span class="fl">0.03</span>) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 98: Not sufficient</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">99</span>, <span class="at">prob =</span> <span class="fl">0.03</span>) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 99: Sufficient</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can make this sample size visually intuitive by showing the binomial(<span class="math inline">\(k\)</span> | 99, 0.03) distribution and highlighting the probability for <span class="math inline">\(k = 0\)</span>. This probability is lower than the required sampling risk <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-13_49f19d2b934a846b46d8b49a919ae765">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="expected-misstatements-1" class="level4" data-number="3.3.1.2">
<h4 data-number="3.3.1.2" class="anchored" data-anchor-id="expected-misstatements-1"><span class="header-section-number">3.3.1.2</span> Expected Misstatements</h4>
<p>However, if the number of expected misstatements in the sample is non-zero, it becomes more difficult to solve the formula for <span class="math inline">\(n\)</span>. Hence, they will need to set <span class="math inline">\(k\)</span> to a different integer value, which consequently determines how the sample size is calculated. Here, we can iteratively try every value of <span class="math inline">\(n\)</span> and return the smallest integer that satisfies the sampling objectives.</p>
<p>In <strong>jfa</strong>, this can be done by adjusting the <code>expected</code> argument in the <code>planning()</code> function. For example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of one expected misstatement in the sample is <span class="math inline">\(n = 157\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-14_95eb44d3fb8678a2ec23aeaf8dba74e3">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">1</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"binomial"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 157 </span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 156 iterations via method 'binomial'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once again, the sample size of 157 can be confirmed by checking that 157 is the minimum integer that results in less than 5% probability of finding 0 or 1 misstatements, given the assumption that the population misstatement is truly 3%.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-15_3509872b317cb2e4981318012c9c35d4">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">156</span>, <span class="at">prob =</span> <span class="fl">0.03</span>)) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 156: Not sufficient</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">size =</span> <span class="dv">157</span>, <span class="at">prob =</span> <span class="fl">0.03</span>)) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 157: Sufficient</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like before, we can make this sample size visually intuitive by showing the binomial(<span class="math inline">\(k\)</span> | 157, 0.03) distribution and highlighting the probabilities for <span class="math inline">\(k = 0\)</span> and <span class="math inline">\(k = 1\)</span>. The sum of these probabilities is lower than the required sampling risk <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-16_94caec605eb84171d413f740b6c1bd62">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="partial-expected-misstatements" class="level4" data-number="3.3.1.3">
<h4 data-number="3.3.1.3" class="anchored" data-anchor-id="partial-expected-misstatements"><span class="header-section-number">3.3.1.3</span> Partial Expected Misstatements</h4>
<p>When the expected misstatements in the sample <span class="math inline">\(\theta_{exp}\)</span> is assessed, the value for <span class="math inline">\(k\)</span> can be determined as <span class="math inline">\(k = n\theta_{exp}\)</span>, which consequently determines how the sample size can be calculated.</p>
<p>To account for the fact that <span class="math inline">\(k\)</span> can have non-integer values in this case, we can use a well-known similarity between the binomial distribution and the beta distribution to plan the sample size. The upper bound for any binomial(<span class="math inline">\(k\)</span>; <span class="math inline">\(n\)</span>, <span class="math inline">\(\theta\)</span>) distributed variable can also be obtained via percentiles of the beta(<span class="math inline">\(1 + k\)</span>, <span class="math inline">\(n - k\)</span>) distribution. For example, the upper bound for the outcomes below is the same, regardless of whether it is computed via the binomial or the beta distribution.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-17_ce1a2b5cceadbc94ece8a9713bc85128">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>ub_binom <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(<span class="at">x =</span> k, <span class="at">n =</span> n, <span class="at">p =</span> <span class="fl">0.03</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">alternative =</span> <span class="st">"less"</span>)<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>ub_beta <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">shape1 =</span> <span class="dv">1</span> <span class="sc">+</span> k, <span class="at">shape2 =</span> n <span class="sc">-</span> k)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>ub_binom <span class="sc">==</span> ub_beta</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This relationship between the binomial likelihood and the beta distribution is deliberately <strong>not</strong> used in <strong>jfa</strong>. That is because, in the case of the binomial distrib ution, auditing standards round the tolerable misstatements upwards to a whole number <span class="citation" data-cites="AICPA-A">(<a href="chref.html#ref-AICPA-A" role="doc-biblioref">American Institute of Certified Public Accountants (AICPA), 2016</a>)</span>. For example, if we try to use want to use <code>expected = 1.5</code>, <strong>jfa</strong> will use <code>2</code> as the expected misstatements. The resulting sample size is <span class="math inline">\(n = 208\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-18_7191cb4c0a2a8de55cd5b4f93b899bf3">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="fl">1.5</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"binomial"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Using 'expected = 2' since 'expected' must be a single integer &gt;= 0</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 208 </span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 206 iterations via method 'binomial'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="bayesian-planning-1" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="bayesian-planning-1"><span class="header-section-number">3.3.2</span> Bayesian Planning</h3>
<p>Performing Bayesian planning with the binomial likelihood requires that you specify a prior distribution for the parameter <span class="math inline">\(\theta\)</span>. Practically, this means that you should provide an input for the <code>prior</code> argument in the <code>planning()</code> function.</p>
<p>Setting <code>prior = TRUE</code> performs Bayesian planning using a <a href="https://koenderks.github.io/jfa/articles/creating-prior.html#default-priors-method-default">default prior</a> conjugate to the specified <code>likelihood</code> (i.e., a beta prior). Concretely, this means that the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{align}
  k &amp;\sim \text{Binomial}(n, \theta) \\
  \theta &amp;\sim \text{Beta}(\alpha, \beta)
\end{align}\]</span></p>
<blockquote class="blockquote">
<p>The beta prior distribution is conjugate to the binomial likelihood (see this <a href="https://en.wikipedia.org/wiki/Conjugate_prior#Table_of_conjugate_distributions">list</a> of conjugate priors), which means that the posterior distribution of <span class="math inline">\(\theta\)</span> can be determined analytically. For example, if the prior distribution is beta(<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>) and the auditor has observed a sample of <span class="math inline">\(n\)</span> items containing <span class="math inline">\(k\)</span> misstatements, the posterior distribution for <span class="math inline">\(\theta\)</span> is beta(<span class="math inline">\(\alpha + k\)</span>, <span class="math inline">\(\beta + n - k\)</span>).</p>
</blockquote>
<p>For example, the command below uses a default beta(<span class="math inline">\(\alpha=1\)</span>, <span class="math inline">\(\beta=1\)</span>) prior distribution to plan the sample, since <code>planning()</code> is given the binomial likelihood. If we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha=0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of zero expected misstatements in the sample is <span class="math inline">\(n = 98\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-19_24b86e5856115352929ea075a11283a2">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>plan <span class="ot">&lt;-</span> <span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">likelihood =</span> <span class="st">"binomial"</span>, <span class="at">prior =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plan)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning Summary</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Confidence level:              0.95 </span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Materiality:                   0.03 </span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Hypotheses:                    H₀: Θ &gt; 0.03 vs. H₁: Θ &lt; 0.03 </span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected:                      0 </span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    binomial </span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Prior distribution:            beta(α = 1, β = 1) </span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Minimum sample size:           98 </span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Tolerable errors:              0 </span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Posterior distribution:        beta(α = 1, β = 99) </span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected most likely error:    0 </span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected upper bound:          0.029807 </span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected precision:            0.029807 </span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected BF₁₀:                 627.22</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can inspect how the prior distribution compares to the expected posterior distribution by using the <code>plot()</code> function. The expected posterior distribution is the posterior distribution that would occur if you actually observed the planned sample containing the expected misstatements.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-20_60e1e25c9752acba1a8428b0a9403f27">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The input for the <code>prior</code> argument can also be an object created by the <code>auditPrior</code> function. If <code>planning()</code> receives a prior for which there is no conjugate likelihood available, it will numerically derive the posterior distribution. For example, the command below uses a Normal(0, 0.05) prior distribution to plan the sample using the binomial likelihood. Concretely, this means that the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{align}
  k &amp;\sim \text{Binomial}(n, \theta) \\
  \theta &amp;\sim \text{Normal}(\mu = 0, \sigma = 0.05)
\end{align}\]</span></p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-21_0c5d6665f9ed61b1828d09faa193ed87">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">auditPrior</span>(<span class="at">method =</span> <span class="st">"param"</span>, <span class="at">likelihood =</span> <span class="st">"normal"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">beta =</span> <span class="fl">0.05</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plan <span class="ot">&lt;-</span> <span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">likelihood =</span> <span class="st">"poisson"</span>, <span class="at">prior =</span> prior)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plan)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning Summary</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Confidence level:              0.95 </span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Materiality:                   0.03 </span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Hypotheses:                    H₀: Θ &gt; 0.03 vs. H₁: Θ &lt; 0.03 </span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected:                      0 </span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    poisson </span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Prior distribution:            normal(μ = 0, σ = 0.05)T[0,1] </span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Minimum sample size:           90 </span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Tolerable errors:              0 </span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Posterior distribution:        Determined via MCMC sampling </span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected most likely error:    0.0008648 </span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected upper bound:          0.029029 </span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected precision:            0.028164 </span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected BF₁₀:                 19.08</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The resulting sample size under this prior is <span class="math inline">\(n = 90\)</span>, a reduction of 8 samples when compared to the default beta(1, 1) prior distribution.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-22_5e2cf13cbac5d517eae006e26dad7918">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="the-poisson-likelihood" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="the-poisson-likelihood"><span class="header-section-number">3.4</span> The Poisson Likelihood</h2>
<p>Let’s consider how to use the Poisson likelihood to calculate the minimum sample size needed to achieve the desired level of assurance. The Poisson distribution is a discrete probability distribution that is commonly used to model the number of events occurring in a fixed time or space. We can use the Poisson distribution as a likelihood to model the number of misstatements that are expected to be found in the sample.</p>
<blockquote class="blockquote">
<p>In audit sampling, the Poisson likelihood is often used to approximate the binomial likelihood since it is easier to work with (i.e., it only has one parameter: <span class="math inline">\(\lambda\)</span>, while the binomial has two parameters: <span class="math inline">\(\theta\)</span> and <span class="math inline">\(n\)</span>). However, the Poisson likelihood is more conservative than the binomial likeliood, meaning that resulting sample sizes will be higher.</p>
</blockquote>
<p>The probability mass function (PMF) of the Poisson distribution is given by:</p>
<p><span class="math display">\[\begin{equation}
  p(k; \lambda) = \frac{\lambda^k e^{-\lambda}}{k!},
\end{equation}\]</span></p>
<p>where <span class="math inline">\(k\)</span> is the number of misstatements in the sample, and <span class="math inline">\(\lambda\)</span> is the average number of misstatements expected in the sample. The average number of misstatements is related to the misstatement rate in the population, denoted by <span class="math inline">\(\theta\)</span>, and the sample size, <span class="math inline">\(n\)</span>, by the following equation:</p>
<p><span class="math display">\[\begin{equation}
  \lambda = n \theta.
\end{equation}\]</span></p>
<section id="classical-planning-2" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="classical-planning-2"><span class="header-section-number">3.4.1</span> Classical planning</h3>
<p>Concretely, the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{equation}
  k \sim \text{Poisson}(n \theta_{max})
\end{equation}\]</span></p>
<section id="no-expected-misstatement-2" class="level4" data-number="3.4.1.1">
<h4 data-number="3.4.1.1" class="anchored" data-anchor-id="no-expected-misstatement-2"><span class="header-section-number">3.4.1.1</span> No Expected Misstatement</h4>
<p>Given the performance materiality <span class="math inline">\(\theta_{max}\)</span> and the Poisson likelihood, we can solve for the minimum sample size <span class="math inline">\(n\)</span> needed to achieve a certain assurance level. A useful trick to utilize is that, if we do not expect any misstatements in the sample, the formula for the required sample size reduces to:</p>
<p><span class="math display">\[\begin{equation}
  n = \lceil-\frac{\ln(\alpha)}{\theta_{max}}\rceil.
\end{equation}\]</span></p>
<blockquote class="blockquote">
<p><span class="math inline">\(\lceil...\rceil\)</span> is the ceiling function. Hence, <span class="math inline">\(\lceil1.2\rceil = 2\)</span>.</p>
</blockquote>
<p>For example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of zero expected misstatements in the sample is <span class="math inline">\(n = 100\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-23_1b05103a4dd1b6a238c84212a7edbe71">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(<span class="sc">-</span><span class="fu">log</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>) <span class="sc">/</span> <span class="fl">0.03</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <strong>jfa</strong>, this sample size can be replicated using the following code:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-24_d5d20afe9aaf9a2f05e154d8a653738c">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"poisson"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 100 </span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 101 iterations via method 'poisson'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The sample size of 100 can be confirmed by checking that 100 is the minimum integer that results in less than 5% probability of finding 0 misstatements, given the assumption that the population misstatement is truly 3%. The <code>dpois()</code> function calculates the probability of observing <span class="math inline">\(k\)</span> missatements in a sample of <span class="math inline">\(n\)</span> items given an assumed misstatement probability <span class="math inline">\(\theta_{max}\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-25_11e652c8d9d1e78e2289d4b2536a1688">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">lambda =</span> <span class="dv">99</span> <span class="sc">*</span> <span class="fl">0.03</span>) <span class="sc">&lt;</span> <span class="fl">0.05</span>  <span class="co"># 99:  Not sufficient</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">lambda =</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fl">0.03</span>) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 100: Sufficient</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can make this visually intuitive by showing the Poisson(<span class="math inline">\(k\)</span> | 100 * 0.03) distribution and highlighting the probability for <span class="math inline">\(k = 0\)</span>. This probability is lower than the required sampling risk <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-26_5f0ae21628b60ce6eca3fe8777667df3">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="expected-misstatements-2" class="level4" data-number="3.4.1.2">
<h4 data-number="3.4.1.2" class="anchored" data-anchor-id="expected-misstatements-2"><span class="header-section-number">3.4.1.2</span> Expected Misstatements</h4>
<p>However, if the number of expected misstatements in the sample is non-zero, it becomes more difficult to solve the formula for <span class="math inline">\(n\)</span> algebraically. Hence, they will need to set <span class="math inline">\(k\)</span> to a different integer value. Next, we can iteratively try every value of <span class="math inline">\(n\)</span> and return the smallest integer that satisfies the sampling objectives.</p>
<p>For example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of one expected misstatement in the sample is <span class="math inline">\(n = 159\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-27_212497874999f78677ad96f266a9e810">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">1</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"poisson"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 159 </span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 158 iterations via method 'poisson'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once again, the sample size of 159 can be confirmed by checking that 159 is the minimum integer that results in less than 5% probability of finding 0 or 1 misstatements, given the assumption that the population misstatement is truly 3%.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-28_87099a529457b8fc36c63a9bc08c18ca">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">lambda =</span> <span class="dv">158</span> <span class="sc">*</span> <span class="fl">0.03</span>)) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 158: Not sufficient</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dpois</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">lambda =</span> <span class="dv">159</span> <span class="sc">*</span> <span class="fl">0.03</span>)) <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="co"># 159: Sufficient</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Like before, we can make this visually intuitive by showing the Poisson(<span class="math inline">\(k\)</span> | 159 * 0.03) distribution and highlighting the probabilities for <span class="math inline">\(k = 0\)</span> and <span class="math inline">\(k = 1\)</span>. The sum of these probabilities is lower than the required sampling risk <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-29_42c316d933874b959f2027aa0ab8d6ae">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="partial-expected-misstatements-1" class="level4" data-number="3.4.1.3">
<h4 data-number="3.4.1.3" class="anchored" data-anchor-id="partial-expected-misstatements-1"><span class="header-section-number">3.4.1.3</span> Partial Expected Misstatements</h4>
<p>When the expected misstatements in the sample <span class="math inline">\(\theta_{exp}\)</span> is assessed, the value for <span class="math inline">\(k\)</span> can be determined as <span class="math inline">\(k = n\theta_{exp}\)</span>, which consequently determines how the sample size can be calculated.</p>
<p>To account for the fact that <span class="math inline">\(k\)</span> can have non-integer values in this case, we use a well-known similarity between the Poisson distribution and the gamma distribution to plan the sample size. The upper bound for any Poisson(<span class="math inline">\(k\)</span>; <span class="math inline">\(n \theta\)</span>) distributed variable can also be obtained via percentiles of the gamma(<span class="math inline">\(1 + k\)</span>, <span class="math inline">\(n\)</span>) distribution. For example, the upper bound for the outcomes below is the same, regardless of whether it is computed via the Poisson or the gamma distribution.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-30_9a26efd098254497f0522f093aa4c385">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>ub_pois <span class="ot">&lt;-</span> <span class="fu">poisson.test</span>(<span class="at">x =</span> k, <span class="at">T =</span> n, <span class="at">r =</span> <span class="fl">0.03</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">alternative =</span> <span class="st">"less"</span>)<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>ub_gamma <span class="ot">&lt;-</span> <span class="fu">qgamma</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">shape =</span> <span class="dv">1</span> <span class="sc">+</span> k, <span class="at">rate =</span> n)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>ub_pois <span class="sc">==</span> ub_gamma</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This relationship between the Poisson likelihood and the gamma distribution is used under the hood in <strong>jfa</strong>. For example, if we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha = 0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of 1.5 expected misstatements in the sample is <span class="math inline">\(n = 185\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-31_55d3c7c5fec98a5abe61f8cf2f019eb8">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="fl">1.5</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood =</span> <span class="st">"poisson"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 185 </span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 184 iterations via method 'poisson'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The sample size of 185 can be confirmed by checking that 185 is the minimum integer that results in less than 5% probability of finding a misstatement rate in the population equal to, or higher than, 3%.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-32_2392e149b7d8dbdb0fe7714131b6e511">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qgamma</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">shape =</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">1.5</span>, <span class="at">rate =</span> <span class="dv">184</span>) <span class="sc">&lt;</span> <span class="fl">0.03</span> <span class="co"># 184: Not sufficient</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] FALSE</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qgamma</span>(<span class="at">p =</span> <span class="fl">0.95</span>, <span class="at">shape =</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fl">1.5</span>, <span class="at">rate =</span> <span class="dv">185</span>) <span class="sc">&lt;</span> <span class="fl">0.03</span> <span class="co"># 185: Sufficient</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="bayesian-planning-2" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="bayesian-planning-2"><span class="header-section-number">3.4.2</span> Bayesian Planning</h3>
<p>Performing Bayesian planning with the Poisson likelihood requires that you specify a prior distribution for the parameter <span class="math inline">\(\theta\)</span>. Practically, this means that you should provide an input for the <code>prior</code> argument in the <code>planning()</code> function.</p>
<p>Setting <code>prior = TRUE</code> performs Bayesian planning using a <a href="https://koenderks.github.io/jfa/articles/creating-prior.html#default-priors-method-default">default prior</a> conjugate to the specified <code>likelihood</code> (i.e., a gamma prior). Concretely, this means that the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{align}
  k &amp;\sim \text{Poisson}(n\theta) \\
  \theta &amp;\sim \text{Gamma}(\alpha, \beta)
\end{align}\]</span></p>
<blockquote class="blockquote">
<p>The gamma prior distribution is conjugate to the Poisson likelihood (see this <a href="https://en.wikipedia.org/wiki/Conjugate_prior#Table_of_conjugate_distributions">list</a> of conjugate priors), which means that the posterior distribution of <span class="math inline">\(\theta\)</span> can be determined analytically. For example, if the prior distribution is gamma(<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>) and the auditor has observed a sample of <span class="math inline">\(n\)</span> items containing <span class="math inline">\(k\)</span> misstatements, the posterior distribution for <span class="math inline">\(\theta\)</span> is gamma(<span class="math inline">\(\alpha + k\)</span>, <span class="math inline">\(\beta + n\)</span>).</p>
</blockquote>
<p>For example, the command below uses a default gamma(<span class="math inline">\(\alpha=1\)</span>, <span class="math inline">\(\beta=1\)</span>) prior distribution to plan the sample, since <code>planning()</code> is given the Poisson likelihood. If we want to achieve an assurance level of 95% (<span class="math inline">\(\alpha=0.05\)</span>) for a performance materiality of <span class="math inline">\(\theta_{max} = 0.03\)</span>, then the required sample size under the assumption of zero expected misstatements in the sample is <span class="math inline">\(n = 99\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-33_d559aadffaa4227cb75fa95bc9878120">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plan <span class="ot">&lt;-</span> <span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">likelihood =</span> <span class="st">"poisson"</span>, <span class="at">prior =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plan)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning Summary</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Confidence level:              0.95 </span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Materiality:                   0.03 </span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Hypotheses:                    H₀: Θ &gt; 0.03 vs. H₁: Θ &lt; 0.03 </span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected:                      0 </span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    poisson </span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Prior distribution:            gamma(α = 1, β = 1) </span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Minimum sample size:           99 </span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Tolerable errors:              0 </span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Posterior distribution:        gamma(α = 1, β = 100) </span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected most likely error:    0 </span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected upper bound:          0.029957 </span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected precision:            0.029957 </span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected BF₁₀:                 626.69</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can inspect how the prior distribution compares to the expected posterior distribution by using the <code>plot()</code> function. The expected posterior distribution is the posterior distribution that would occur if you actually observed the planned sample containing the expected misstatements.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-34_8caecbe8bf931ae67f2092b783b3bc8e">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The input for the <code>prior</code> argument can also be an object created by the <code>auditPrior</code> function. If <code>planning()</code> receives a prior for which there is no conjugate likelihood available, it will numerically derive the posterior distribution. For example, the command below uses a Normal(0, 0.05) prior distribution to plan the sample using the Poisson likelihood. Concretely, this means that the following statistical model is assumed:</p>
<p><span class="math display">\[\begin{align}
  k &amp;\sim \text{Poisson}(n\theta) \\
  \theta &amp;\sim \text{Normal}(\mu = 0, \sigma = 0.05)
\end{align}\]</span></p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-35_9eb6954b2d1fab9daa14bed06ec2027a">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">auditPrior</span>(<span class="at">method =</span> <span class="st">"param"</span>, <span class="at">likelihood =</span> <span class="st">"normal"</span>,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">beta =</span> <span class="fl">0.05</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>plan <span class="ot">&lt;-</span> <span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> <span class="dv">0</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">likelihood =</span> <span class="st">"poisson"</span>, <span class="at">prior =</span> prior)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(plan)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning Summary</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Confidence level:              0.95 </span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Materiality:                   0.03 </span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Hypotheses:                    H₀: Θ &gt; 0.03 vs. H₁: Θ &lt; 0.03 </span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected:                      0 </span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    poisson </span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Prior distribution:            normal(μ = 0, σ = 0.05)T[0,1] </span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Minimum sample size:           91 </span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Tolerable errors:              0 </span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Posterior distribution:        Determined via MCMC sampling </span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected most likely error:    0.0010232 </span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected upper bound:          0.029029 </span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected precision:            0.028006 </span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Expected BF₁₀:                 19.296</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The resulting sample size under this prior is <span class="math inline">\(n = 91\)</span>, a reduction of 8 samples when compared to the default gamma(1, 1) prior.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-36_bfa081672cd1e40583c1eb07fd0d545c">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="practical-examples" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="practical-examples"><span class="header-section-number">3.5</span> Practical Examples</h2>
<p>This section contains practical examples of how to conduct the planning of statistical audit samples and demonstrates how to set up a prior distribution based on various types of relevant audit information.</p>
<section id="audit-risk-model" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="audit-risk-model"><span class="header-section-number">3.5.1</span> Audit Risk Model</h3>
<p>In our first example, an auditor is performing tests of details on a population of the auditee. For instance, let’s say an auditor is performing an audit on a company’s accounts payable transactions. The company has a total of <span class="math inline">\(N\)</span> = 1000 accounts payable transactions for the year. Rather than testing all 1000 transactions, the auditor can choose to test a sample of the transactions. The performance materiality for the payable transactions account is set to <span class="math inline">\(\theta_{max}\)</span> = 3%, and the audit risk is set to <span class="math inline">\(\alpha = 0.05\)</span>, or 5%. Based on the results of last years audit, where the most likely estimate of the misstatement was 1%, the auditor wants to tolerate 1% misstatements in the sample before giving an unqualified opinion on the population.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-37_aaaa4a4a3e37349869afc0cbf0e4740d">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ar          <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co"># Audit risk</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>materiality <span class="ot">&lt;-</span> <span class="fl">0.03</span> <span class="co"># Performance materiality</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>expected    <span class="ot">&lt;-</span> <span class="fl">0.01</span> <span class="co"># Tolerable deviation rate</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before tests of details, the auditor has assessed risk of material misstatement via the audit risk model. In this example, the auditor has assessed the effectiveness of the company’s internal controls, such as its segregation of duties and its risk management processes, and has determined that they are sufficient to prevent or detect material misstatements. Because the internal control systems were effective, the auditor assesses the control risk as medium. The auditor’s firm defines the risk categories low, medium, and high respectively as 50%, 60%, and 100%. According to the Audit Risk Model, the detection risk can be calculated as a function of the audit risk, the inherent risk and the control risk.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-38_ed2cd66fc6bfd9854c806afde0ab6fc4">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>ir <span class="ot">&lt;-</span> <span class="dv">1</span>              <span class="co"># Inherent risk</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>cr <span class="ot">&lt;-</span> <span class="fl">0.6</span>            <span class="co"># Control risk</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>dr <span class="ot">&lt;-</span> ar <span class="sc">/</span> (ir <span class="sc">*</span> cr) <span class="co"># Detection risk</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>dr</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.08333333</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By using the detection risk of 8.33% as the sampling risk for this population, the auditor can plan for a sample while taking into account the risk-reducing information. The required minimum sample size is 174 in this case.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-39_8cddd4121a8fe6093e6fbf3d108106c7">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> expected, <span class="at">conf.level =</span> <span class="dv">1</span> <span class="sc">-</span> dr)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Classical Audit Sample Planning</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 174 </span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 175 iterations via method 'poisson'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The example above is a frequentist one. However, the auditor is free to apply a Bayesian philosophy in planning the sample. For example, the risk assessments from the ARM can be incorporated into a prior distribution. This can be done using <code>method = "arm"</code> in the <code>auditPrior()</code> function, which takes the values of the inherent risk probability <code>ir</code> and the control risk probability <code>cr</code>. Hence, the prior distribution in this example can be constructed using the following command:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-40_451bec242cbff57775f37ff3a80a884e">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">auditPrior</span>(<span class="at">method =</span> <span class="st">"arm"</span>, <span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> expected,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ir =</span> ir, <span class="at">cr =</span> cr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>summary()</code> function can be used to obtain relevant information about the prior distribution.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-41_7350e50a7a7e5845a568aaf6b9a5f124">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(prior)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Prior Distribution Summary</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    poisson </span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Specifics:                     ir = 1; cr = 0.6; dr = 0.0833333 </span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Functional form:               gamma(α = 1.46, β = 46) </span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Mode:                          0.01 </span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Mean:                          0.031739 </span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Median:                        0.024859 </span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Variance:                      0.00069 </span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Skewness:                      1.6552 </span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Information entropy (nat):     -2.4894 </span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   95 percent upper bound:        0.08343 </span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Precision:                     0.07343</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Furthermore, the prior distribution can be visualized with a call to the <code>plot()</code> function.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-42_248b42e914eba86f11905978455889c5">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prior)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>By using the prior distribution to incorporate the assessments of the inherent risk and the control risk, the auditor can plan a sample while taking into account the risk-reducing information. The required minimum sample size is also 174 in this case.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-43_0926c9ae2481df4793a4519da9a3cfb1">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.03</span>, <span class="at">expected =</span> expected, <span class="at">conf.level =</span> <span class="dv">1</span> <span class="sc">-</span> ar,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">prior =</span> prior)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 174 </span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 175 iterations via method 'poisson' + 'prior'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="benchmark-analysis" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="benchmark-analysis"><span class="header-section-number">3.5.2</span> Benchmark Analysis</h3>
<p>The auditor may incorporate information obtained through analytical procedures <span class="citation" data-cites="Derks2021">(<a href="chref.html#ref-Derks2021" role="doc-biblioref">Derks et al., 2021</a>)</span>, such as a benchmark analysis, into the prior distribution for <span class="math inline">\(\theta\)</span>. While we have previously discussed methods for constructing a prior distribution based on existing knowledge, there is no set procedure for incorporating information obtained through analytical procedures, as these procedures can vary significantly depending on the type of information being incorporated into the prior distribution. Therefore, it is important to thoroughly substantiate the data and assumptions used in this approach and to carefully consider how these assumptions are incorporated into the prior distribution.</p>
<p>One way to construct a prior distribution on the basis of data is through the use of regression models, such as benchmarking the relationship between sales and costs of sales within the auditee’s specific industry sector. The <strong>jfa</strong> package includes a data set <code>benchmark</code> that can be used for this example.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-44_8bc1c2107918f2b37603947afa92109a">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(benchmark)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(benchmark)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       sales costofsales</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 186273256   140755372</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 336491541   248675452</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 222693077   164299866</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 364905221   285768790</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 382140185   280187371</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 113666950   101552955</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The auditee’s the sum of the sales is $298,112,312 and the sum of the booked costs of sales is $223,994,405, respectively. This is indicated by a blue dot in the figure below, which visualizes the industry sales versus the cost of sales.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-45_dcf740bb05a572390288fa5785a0209c">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The relationship between the sales <span class="math inline">\(S\)</span> and the cost of sales <span class="math inline">\(C\)</span> can be modelled by a linear equation:</p>
<p><span class="math display">\[\begin{equation}
  C = \beta_0 + \beta_1 \cdot S + \epsilon.
\end{equation}\]</span></p>
<p>In practice, this relationship is often more complex than is presented above, and the auditor must carefully construct and evaluate the applied regression model. However, for ease of understanding we will continue our example with this simplified model. The auditor can estimate the regression model using the following command:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-46_012d4039197acf6b89ee5f3ad44cdd89">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(costofsales <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sales, <span class="at">data =</span> benchmark)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; lm(formula = costofsales ~ 1 + sales, data = benchmark)</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Residuals:</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       Min        1Q    Median        3Q       Max </span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; -25736696  -7052141   -226945   6857840  25498106 </span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; (Intercept) 2.413e+05  3.455e+06    0.07    0.944    </span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sales       7.366e-01  1.310e-02   56.21   &lt;2e-16 ***</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; ---</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Residual standard error: 11150000 on 98 degrees of freedom</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Multiple R-squared:  0.9699, Adjusted R-squared:  0.9696 </span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; F-statistic:  3160 on 1 and 98 DF,  p-value: &lt; 2.2e-16</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The predicted cost of sales for the auditee, based on the industry benchmark, can be computed as follows:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-47_eaf04b88106aa2057063ed9a412eda94">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>C_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">sales =</span> <span class="dv">298112312</span>),</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.90</span>)[<span class="dv">1</span>]</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>C_hat</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 219817866</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The fitted regression line and the predicted cost of sales (red dot) are visualized in the figure below:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-48_646e38ccce4b6f13be079b4796bed4d4">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The prior distribution can be justified by the data and the auditee’s numerical prediction of the cost of sales. In this analytical procedure, the prior distribution on <span class="math inline">\(\theta\)</span> can utilize the relative error distribution from the linear regression. This relative error distribution, which is a Normal(<span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>) distribution, captures the uncertainty of the prediction of the cost of sales through the use of linear regression, scaled to be a percentage of the total cost of sales. The mean <span class="math inline">\(\mu\)</span> of the prior distribution is determined by the relative deviation of the auditee’s booked cost of sales when compared to the predicted cost of sales according to the benchmark data <span class="math inline">\(\frac{C - \hat{C}}{C}\)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-49_23803b21c2f2870dc409ba65bd614357">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> (<span class="dv">223994405</span> <span class="sc">-</span> C_hat) <span class="sc">/</span> <span class="dv">223994405</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>mu</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.01864573</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The standard deviation of the prior distribution is expressed through the standard deviation of the distribution of <span class="math inline">\(\epsilon\)</span>:</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-50_24a1310a018b134ceb813f6f01e47ef0">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>stdev <span class="ot">&lt;-</span> <span class="fu">sd</span>(fit<span class="sc">$</span>residuals) <span class="sc">/</span> <span class="dv">223994405</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>stdev</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.04951199</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The Normal(0.019, 0.05) prior distribution can be constructed through a call to <code>auditPrior()</code>, where the likelihood of the prior is specified as <code>normal</code>. We call the function with <code>method = "param"</code> to manually specify the parameters of the prior distribution.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-51_a93bbfcc6c6acda51fd0cf55fb5807de">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">auditPrior</span>(<span class="at">method =</span> <span class="st">"param"</span>, <span class="at">likelihood =</span> <span class="st">"normal"</span>,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">alpha =</span> mu, <span class="at">beta =</span> stdev)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(prior)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Prior Distribution Summary</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Options:</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Likelihood:                    normal </span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Specifics:                     α = 0.0186457; β = 0.049512 </span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Results:</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Functional form:               normal(μ = 0.019, σ = 0.05)T[0,1] </span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Mode:                          0.018646 </span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Mean:                          0.047096 </span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Median:                        0.041335 </span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Variance:                      0.0011116 </span></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Skewness:                      NA </span></span>
<span id="cb42-18"><a href="#cb42-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Information entropy (nat):     -2.1306 </span></span>
<span id="cb42-19"><a href="#cb42-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   95 percent upper bound:        0.11012 </span></span>
<span id="cb42-20"><a href="#cb42-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Precision:                     0.091473</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The specified prior distribution can be visualized using the <code>plot()</code> function.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-52_1f495b5a4c985823b5e9b0e7e7e8b5d3">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prior)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>By using this prior distribution, the required minimum sample size is 50.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-53_5626a9fb10797372f6976e4596d2bc93">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>plan <span class="ot">&lt;-</span> <span class="fu">planning</span>(<span class="at">materiality =</span> <span class="fl">0.05</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">likelihood =</span> <span class="st">"binomial"</span>, <span class="at">prior =</span> prior)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>plan</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Bayesian Audit Sample Planning</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; minimum sample size = 50 </span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample size obtained in 51 iterations via method 'binomial' + 'prior'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can inspect how the prior distribution compares to the expected posterior distribution by using the <code>plot()</code> function.</p>
<div class="cell" data-layout-align="center" data-hash="ch03_cache/html/unnamed-chunk-54_db4e11d6f860767be03e4ce686533a67">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(plan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch03_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="doc-bibliography" style="display: none">
<div id="ref-AICPA-A" class="csl-entry" role="doc-biblioentry">
American Institute of Certified Public Accountants (AICPA). (2016). Appendix <span>A</span>: Attributes statistical sampling tables. In <em>Audit guide: Audit sampling</em>. <a href="https://doi.org/10.1002/9781119448617.app1">https://doi.org/10.1002/9781119448617.app1</a>
</div>
<div id="ref-Derks2021" class="csl-entry" role="doc-biblioentry">
Derks, K., Swart, J. de, Batenburg, P. van, Wagenmakers, E.-J., &amp; Wetzels, R. (2021). Priors in a <span>B</span>ayesian audit: How integration of existing information into the prior distribution can improve audit transparency and efficiency. <em>International Journal of Auditing</em>, <em>25</em>(3), 621–636. <a href="https://doi.org/10.1111/ijau.12240">https://doi.org/10.1111/ijau.12240</a>
</div>
<div id="ref-Dyer1993" class="csl-entry" role="doc-biblioentry">
Dyer, D., &amp; Pierce, R. L. (1993). On the choice of the prior distribution in hypergeometric sampling. <em>Communications in Statistics - Theory and Methods</em>, <em>22</em>(8), 2125–2146. <a href="https://doi.org/10.1080/03610929308831139">https://doi.org/10.1080/03610929308831139</a>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ch02.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Background Information</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ch04.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Selecting a Sample</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Statistical Audit Sampling with R was written by Koen Derks.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>