# Preface {.unnumbered}

This book, **Statistical Audit Sampling with R**, is intended as a practical guide for auditors who wish to employ probability theory in their audit sampling activities. While the focus of this book is exclusively on audit sampling, it aims to discuss the topic from both the classical (frequentist) perspective and the Bayesian perspective. By examining the subject through these two lenses, the book explains the statistical theory behind commonly used audit sampling procedures and demonstrates how to perform these procedures effectively and efficiently in accordance with international auditing standards using the [**jfa**](https://cran.r-project.org/package=jfa) R package.

Audits can be time-consuming and require going through lots of paperwork. But when we find ways to make audits more efficient or understandable, we free up time for auditors to do other important things. They can focus on coming up with new ideas, foster innovation, and adressing the larger problems of our time. This not only helps them grow as individuals but, perhaps more important, sparks a chain reaction that will ripple through the audit. By clearing auditors' time, we pave the way for progress and a future where they can use their talents to make the world a better place.
