on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # run every day at 11:05 PM Pacific
    - cron: '5 7 * * *'
  workflow_dispatch:

name: renderbook

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book to all format
        run: |
          quarto render
      - uses: actions/upload-artifact@v3
        with:
          name: _book
          path: _book/
  
  checkout-and-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ env.GITHUB_PAT }}
       with:
          email: ${{ secrets.EMAIL }}
          build_dir: _book/

