on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # run every day at 11:05 PM Pacific
    - cron: '5 7 * * *'
  workflow_dispatch:

name: renderbook

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown", "remotes"))'
      - name: Install dependencies
        run: Rscript -e 'remotes::install_github("koenderks/stataudbook", dependencies = TRUE)'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v3
        with:
          name: _book
          path: _book/
  
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ env.GITHUB_PAT }}
       with:
          email: ${{ secrets.EMAIL }}
          build_dir: _book/

